package ecs

import "core:encoding/json"

Navigation_Algorithm :: enum {
	A_Star,
	Theta_Star,
}

// NavGrid2D configures a scene-wide raster navigation surface. Runtime grid
// data is generated by the navigation system rather than serialized in JSON.
NavGrid2D :: struct {
	cell_size: f32,
	algorithm: Navigation_Algorithm,
}

// NavAgent2D contains reusable path-query settings. Destinations and current
// paths remain transient runtime state controlled by game systems.
NavAgent2D :: struct {
	radius:           f32,
	repath_interval:  f32,
	arrival_distance: f32,
}

nav_grid_2d_from_json :: proc(data: json.Value) -> (NavGrid2D, bool) {
	object, ok := data.(json.Object)
	if !ok {return {}, false}
	result := NavGrid2D {
		cell_size = 24,
		algorithm = .A_Star,
	}
	if value, found := object["cell_size"]; found {
		result.cell_size, ok = read_number(value)
		if !ok || result.cell_size <= 0 {return {}, false}
	}
	if value, found := object["algorithm"]; found {
		name, string_ok := value.(json.String)
		if !string_ok {return {}, false}
		switch name {
		case "a_star":
			result.algorithm = .A_Star
		case "theta_star":
			result.algorithm = .Theta_Star
		case:
			return {}, false
		}
	}
	return result, true
}

nav_agent_2d_from_json :: proc(data: json.Value) -> (NavAgent2D, bool) {
	object, ok := data.(json.Object)
	if !ok {return {}, false}
	result := NavAgent2D {
		radius           = 8,
		repath_interval  = .25,
		arrival_distance = 4,
	}
	if value, found := object["radius"]; found {
		result.radius, ok = read_number(value)
		if !ok || result.radius <= 0 {return {}, false}
	}
	if value, found := object["repath_interval"]; found {
		result.repath_interval, ok = read_number(value)
		if !ok || result.repath_interval <= 0 {return {}, false}
	}
	if value, found := object["arrival_distance"]; found {
		result.arrival_distance, ok = read_number(value)
		if !ok || result.arrival_distance < 0 {return {}, false}
	}
	return result, true
}
